### ISSUE TITLE
Help Wanted : O'Gorman & Schneider Precipitation Scaling Code for Multi-Dimensional Data

### ISSUE THREAD

**Issue by chaithrast** [huangzq681/Rx1day_decompose_DNA_2022#1]
Hi,

I hope this message finds you well. I am reaching out to seek your expertise regarding a challenge I am facing with precipitation scaling code using multi-dimensional data.

Currently, I am attempting to apply the O'Gorman & Schneider precipitation scaling code to my data, which includes latitude and longitude. However, I am encountering significant processing time issues due to the need to loop over the entire dataset, which is not practical given its size.

I have attempted parallelization as a potential solution to speed up the computations, but unfortunately, it has not been successful.

I am wondering if there might be a more efficient way to utilize the scaling code with multi-dimensional data. Is it possible to vectorize or parallelize the computations to improve performance? I would greatly appreciate any insights or suggestions you might have on how to approach this problem effectively.

Thank you very much for considering my inquiry.

**Comment by huangzq681** [comment]
Hi,

Thank you for reaching out. Firstly, I'd like to inquire about the coding
environment you're utilizing, whether it's Matlab or Python. This is
because Prof. Gorman offers code in both Matlab and Python formats on his
website (https://pog.mit.edu/code.html
<https://www.aidutu.cn/info/link?url=https://pog.mit.edu/code.html>). As
I'm more proficient with Python, I can offer guidance on calculating
precipitation scaling based on my experience with this platform.

Here are two potential solutions that might be beneficial:

   1.

   Consider focusing on extreme precipitation events, such as annual
   maximum one-day precipitation, as this scaling method is specialized for
   extreme precipitation. By doing so, the time dimension of the datasets can
   be significantly reduced.
   2.

   Optimize your code by vectorizing your datasets and employing parallel
   methods such as "Numba" or "xarray.apply_ufunc()". While the latter method
   may present some challenges, I recommend using the Python package "Numba"
   to accelerate your computations. To assist you further, I've included a
   demonstration Python code in this email, which has been adapted from "
   https://github.com/oliverangelil/precip_extremes_scaling
   <https://www.aidutu.cn/info/link?url=https://github.com/oliverangelil/precip_extremes_scaling>
   ".

I hope you find this information helpful.

Best regards, Zeqin

**Comment by chaithrast** [comment]
Hi, 

Thank you for your support and for promptly responding to my inquiry.

I am using the python version of the code you shared from the repository at https://github.com/oliverangelil/precip_extremes_scaling.

I've have extracted the variables (omega, temperature, and surface pressure) corresponding to the dates of annual maximum 1-day precipitation. However, I've encountered an issue when trying to apply "xarray.apply_ufunc()". It seems that the 'saturation_thermodynamics' function is not compatible with my data structure.

Here are the dimensions of the variables I've extracted:

omega: (time, plev, lat, lon)
temperature: (time, plev, lat, lon)
surface pressure: (time, lat, lon)
plevs: np.array([100000., 92500., 85000., 70000., 60000., 50000., 40000., 30000., 25000., 20000., 15000., 10000.])

Could you please provide some suggestions or assistance on how to resolve this issue? Any help or guidance you can offer would be greatly appreciated.

I encountered difficulty with the second link (https://www.aidutu.cn/info/link?url=https://github.com/oliverangelil/precip_extremes_scaling) you shared. The page is not in English, making it challenging for me to follow.

Thank you very much for your time and assistance.

Best regards,

**Comment by huangzq681** [comment]
Hi,

I am sorry that I haven't used "xarray.apply_ufunc()" in this precipitation
scaling calculation. My understanding is that this method is best suited
for simple parallel tasks, making it challenging to use in complicated
computation involving multiple variables and intricate data dimensions. I
did attempt to integrate this method into my computation, however, due to
its complexity, I also failed to calculate the precipitation scaling
successfully. If you come across a way to apply this method effectively in
this calculation, please don't hesitate to let me know.

You might want to explore alternative methods to tackle this issue. For
instance, you could consider employing parallelization techniques such as
"joblib.Parallel" or "multiprocessing," both of which I've used in other
cases but not in this particular case.

The second link I shared is
https://github.com/oliverangelil/precip_extremes_scaling, I don't why there
is a prefix in my reply.

I hope this helps.

Cheers,
Zeqin

**Comment by chaithrast** [comment]
Hi Zeqin,

I appreciate your clarification regarding the use of "xarray.apply_ufunc()".  I'll keep you updated If I find a solution to effectively use "xarray.apply_ufunc()" in this case.

Your suggestion to consider parallelization techniques such as "joblib.Parallel" is noted.        

I have one more query: assuming you utilized the "Numba" package in the scaling computation, could you share some insights or tips on how to effectively incorporate "numba" into the calculation process? I haven't utilized the this package before.        

Once again, I truly appreciate your assistance and guidance in this matter.

**Comment by huangzq681** [comment]
Hi,

Regarding your query about incorporating the "Numba" package into the
calculation process, I'd be happy to provide some insights. Because I just
applied this package in this case study, I didn’t go too deep into the
package itself. Based on my experience, here are some tips for effectively
incorporating “Numba” into your workflow:



   1. *Decide where to use the Numba methods*: As the calculation of
   precipitation scaling involves several procedures, e.g., the calculations
   of saturation thermodynamics, moist adiabatic lapse rate, and so on, you
   need to keep in mind which part of the procedures are the most complicated
   and time-consuming. Some procedures that only involve simple array
   calculation can be well processed by “Numpy” without “Numba”.
   2. *Use Numba decorators:* Numba provides several decorators like ***@***.***”
   and ***@***.***” that can be applied to Python functions to optimize
   them. The former is the most simple decorator to enable compilation with
   “Numba”, however, it did not work for my case. I have checked through the
   code but failed to debug the errors. You can also try different decorators
   with different parameter settings to see if they work. While the latter
   should be more complicated and with several parameters that should be
   particularly aware of, it did work for our calculation of precipitation
   scaling.
   3. * Difference between the decorated functions and the traditional
   ones:* When using a Numba decorator, you should know that the style of
   the function is a little different from the ones we frequently use. For
   example, you don’t need to explicitly include “return” in your function but
   put those return variables as the parameters of the function. In other
   words, both the input and output variables are the parameters of the
   function.  In this case, you will need to include the variable types of
   each variable as one of the parameters of the decorator, as well as specify
   the dimensions along which you need to calculate (from the input variables
   to the output variables).
   4. *Experiment and tine-tune:* Test the performance of your code with
   and without "Numba" optimization. Sometimes, the performance gain may not
   be substantial for certain types of computations. Experimentation will help
   you determine where "Numba" is most effective.


Again, “Numba” is indeed a powerful tool for accelerating numerical
computations and I only know a little about it. I highly recommend you
refer to its official manual (
https://numba.pydata.org/numba-doc/dev/user/5minguide.html) to dig in-depth
into its performance. If you have any further questions or need
clarification on any aspect, please feel free to reach out.

Zeqin

**Comment by huangzq681** [comment]
By the way, I just noticed that I replied to you through my Google mail. So
I am wondering if you can receive my attachment in the former reply since
you were using GitHub to communicate with me.

**Comment by chaithrast** [comment]
Thank you for the heads-up.

Unfortunately, I haven't received any attachments from your previous
message. Would it be possible for you to resend the attachment? If you
encounter any difficulties sending the attachment, could you please send it
to my email address at ***@***.***?

**Comment by huangzq681** [comment]
Sorry for the mistake. However, I can't find your Email
address because it's invisible to me, which I think might be due to the
privacy policy of GitHub.
Could you please reach out to my Email directly? So that I can share the
attachment with you through Email.
My Email address is available in the profile of my GitHub.

**Comment by chaithrast** [comment]
Sorry for the inconvenience caused. I've reached out to you directly via email. 
Looking forward to your response.
